2025-08-07 17:52:34,349 88183 INFO ? odoo: Odoo version 18.0 
2025-08-07 17:52:34,350 88183 INFO ? odoo: Using configuration file at /home/grand-as/psagsn/custom_addons/sama_etat/odoo.conf 
2025-08-07 17:52:34,350 88183 INFO ? odoo: addons paths: ['/var/odoo/odoo18/odoo/addons', '/home/grand-as/.local/share/Odoo/addons/18.0', '/var/odoo/odoo18/addons', '/home/grand-as/psagsn/custom_addons/helpdesk', '/home/grand-as/psagsn/custom_addons'] 
2025-08-07 17:52:34,350 88183 INFO ? odoo: database: odoo@localhost:default 
2025-08-07 17:52:34,494 88183 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf 
2025-08-07 17:52:34,535 88183 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltoimage binary at /usr/bin/wkhtmltoimage 
2025-08-07 17:52:34,759 88183 INFO ? odoo.service.server: HTTP service (werkzeug) running on grand-as-ThinkPad-T560:8070 
2025-08-07 17:52:34,783 88183 INFO sama odoo.modules.loading: loading 1 modules... 
2025-08-07 17:52:34,791 88183 INFO sama odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-08-07 17:52:34,830 88183 INFO sama odoo.modules.loading: loading 60 modules... 
2025-08-07 17:52:35,466 88183 WARNING sama py.warnings: /var/odoo/odoo18/odoo/api.py:484: DeprecationWarning: The model odoo.addons.sama_etat.models.business_models is not overriding the create method in batch
  File "/var/odoo/odoo18/odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "/var/odoo/odoo18/odoo/cli/command.py", line 66, in main
    o.run(args)
  File "/var/odoo/odoo18/odoo/cli/server.py", line 182, in run
    main(args)
  File "/var/odoo/odoo18/odoo/cli/server.py", line 175, in main
    rc = odoo.service.server.start(preload=preload, stop=stop)
  File "/var/odoo/odoo18/odoo/service/server.py", line 1457, in start
    rc = server.run(preload, stop)
  File "/var/odoo/odoo18/odoo/service/server.py", line 622, in run
    rc = preload_registries(preload)
  File "/var/odoo/odoo18/odoo/service/server.py", line 1361, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/odoo/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/var/odoo/odoo18/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/var/odoo/odoo18/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/var/odoo/odoo18/odoo/modules/loading.py", line 365, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/var/odoo/odoo18/odoo/modules/loading.py", line 186, in load_module_graph
    load_openerp_module(package.name)
  File "/var/odoo/odoo18/odoo/modules/module.py", line 384, in load_openerp_module
    __import__(qualname)
  File "/home/grand-as/psagsn/custom_addons/sama_etat/__init__.py", line 1, in <module>
    from . import models
  File "/home/grand-as/psagsn/custom_addons/sama_etat/models/__init__.py", line 1, in <module>
    from . import business_models
  File "/home/grand-as/psagsn/custom_addons/sama_etat/models/business_models.py", line 4, in <module>
    class GovernmentProject(models.Model):
  File "/home/grand-as/psagsn/custom_addons/sama_etat/models/business_models.py", line 191, in GovernmentProject
    @api.model
  File "/var/odoo/odoo18/odoo/api.py", line 431, in model
    return model_create_single(method)
  File "/var/odoo/odoo18/odoo/api.py", line 484, in model_create_single
    warnings.warn(
 
2025-08-07 17:52:35,476 88183 INFO sama odoo.addons.sama_etat: Loading sama_etat module Python files... 
2025-08-07 17:52:35,477 88183 INFO sama odoo.modules.loading: 60 modules loaded in 0.65s, 0 queries (+0 extra) 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.project.name: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.project.localisation_geographique: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.project.secteur_intervention: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.project.duree_previsionnelle: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.project.start_date: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.project.end_date: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.project.cout_total_projet: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.project.currency_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.project.modalites_gestion_financiere: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.project.ligne_budgetaire_rattachement: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.decision.title: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.decision.reference: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,619 88183 WARNING sama odoo.fields: Field government.decision.decision_type: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.decision_date: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.document: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.document_name: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.description: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.strategic_objective_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.project_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.event_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.ministry_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.is_public: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.implementation_status: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.implementation_deadline: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.responsible_user_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.progress_percentage: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.last_follow_up_date: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.next_follow_up_date: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.follow_up_notes: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.latitude: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.decision.longitude: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.event.latitude: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.event.longitude: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.event.name: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,620 88183 WARNING sama odoo.fields: Field government.event.event_date: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.event.date_start: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.event.date_end: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.event.location: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.event.organizer_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.event.event_type: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.event.description: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.event.project_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.event.strategic_objective_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.budget.name: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.budget.fiscal_year: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.budget.allocated_amount: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.budget.used_amount: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.budget.currency_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.budget.budget_type: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.budget.ministry_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.budget.strategic_objective_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,621 88183 WARNING sama odoo.fields: Field government.budget.description: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,622 88183 WARNING sama odoo.fields: Field government.ministry.name: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,622 88183 WARNING sama odoo.fields: Field government.ministry.code: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,622 88183 WARNING sama odoo.fields: Field government.ministry.type: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,622 88183 WARNING sama odoo.fields: Field government.ministry.description: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,622 88183 WARNING sama odoo.fields: Field government.ministry.address: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,622 88183 WARNING sama odoo.fields: Field government.ministry.phone: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,622 88183 WARNING sama odoo.fields: Field government.ministry.email: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,622 88183 WARNING sama odoo.fields: Field government.ministry.website: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,622 88183 WARNING sama odoo.fields: Field strategic.plan.name: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,623 88183 WARNING sama odoo.fields: Field strategic.plan.vision: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,623 88183 WARNING sama odoo.fields: Field strategic.plan.start_date: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,623 88183 WARNING sama odoo.fields: Field strategic.plan.end_date: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,623 88183 WARNING sama odoo.fields: Field strategic.plan.pillar_ids: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,623 88183 WARNING sama odoo.fields: Field strategic.pillar.name: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,623 88183 WARNING sama odoo.fields: Field strategic.pillar.code: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,623 88183 WARNING sama odoo.fields: Field strategic.pillar.plan_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,623 88183 WARNING sama odoo.fields: Field strategic.pillar.description: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,623 88183 WARNING sama odoo.fields: Field strategic.pillar.axis_ids: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,623 88183 WARNING sama odoo.fields: Field strategic.axis.name: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,623 88183 WARNING sama odoo.fields: Field strategic.axis.code: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,623 88183 WARNING sama odoo.fields: Field strategic.axis.description: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.axis.pillar_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.axis.objective_ids: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.objective.name: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.objective.code: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.objective.axis_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.objective.description: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.objective.kpi_ids: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.objective.linked_projects: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.objective.linked_decisions: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.objective.linked_budgets: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.objective.linked_events: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.kpi.name: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.kpi.code: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.kpi.objective_id: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,624 88183 WARNING sama odoo.fields: Field strategic.kpi.description: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,625 88183 WARNING sama odoo.fields: Field strategic.kpi.target_value: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,625 88183 WARNING sama odoo.fields: Field strategic.kpi.current_value: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,625 88183 WARNING sama odoo.fields: Field strategic.kpi.unit_of_measure: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,625 88183 WARNING sama odoo.fields: Field strategic.kpi.date_updated: unknown parameter 'states', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2025-08-07 17:52:35,662 88183 INFO sama odoo.modules.loading: Modules loaded. 
2025-08-07 17:52:35,669 88183 INFO sama odoo.modules.registry: Registry loaded in 0.908s 
2025-08-07 17:52:35,696 88183 INFO sama odoo.addons.base.models.ir_http: Generating routing map for key 1 
2025-08-07 17:52:35,778 88183 INFO sama werkzeug: 127.0.0.1 - - [07/Aug/2025 17:52:35] "GET /websocket?version=18.0-5 HTTP/1.1" 101 - 9 0.009 0.857
2025-08-07 17:52:36,114 88183 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres 
2025-08-07 18:00:59,994 88183 INFO sama werkzeug: 127.0.0.1 - - [07/Aug/2025 18:00:59] "HEAD / HTTP/1.1" 200 - 148 0.128 0.791
2025-08-07 18:01:29,102 88183 INFO sama werkzeug: 127.0.0.1 - - [07/Aug/2025 18:01:29] "HEAD / HTTP/1.1" 200 - 5 0.005 0.030
2025-08-07 18:02:10,481 88183 INFO sama odoo.addons.base.models.ir_attachment: _read_file reading /home/grand-as/.local/share/Odoo/filestore/sama/f3/f31bdf173e5748b875ca5e389e1edba54b4bff25 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
        ~^^^^^
  File "/var/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x701641bef2e0>, 2, '', ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/addons/base/models/ir_attachment.py", line 122, in _file_read
    with open(full_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce nom: '/home/grand-as/.local/share/Odoo/filestore/sama/f3/f31bdf173e5748b875ca5e389e1edba54b4bff25'
2025-08-07 18:02:10,483 88183 INFO sama odoo.addons.base.models.ir_attachment: _read_file reading /home/grand-as/.local/share/Odoo/filestore/sama/aa/aa2cad94340900f9e642750f42295ca97ab0ec81 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
        ~^^^^^
  File "/var/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x701641bef2e0>, 2, '', ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/addons/base/models/ir_attachment.py", line 122, in _file_read
    with open(full_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce nom: '/home/grand-as/.local/share/Odoo/filestore/sama/aa/aa2cad94340900f9e642750f42295ca97ab0ec81'
2025-08-07 18:02:10,484 88183 INFO sama odoo.addons.base.models.ir_attachment: _read_file reading /home/grand-as/.local/share/Odoo/filestore/sama/37/3709cc2e0d5df4c199f96c6d07e2aaf29a63bcba 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
        ~^^^^^
  File "/var/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x701641bef2e0>, 2, '', ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/addons/base/models/ir_attachment.py", line 122, in _file_read
    with open(full_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce nom: '/home/grand-as/.local/share/Odoo/filestore/sama/37/3709cc2e0d5df4c199f96c6d07e2aaf29a63bcba'
2025-08-07 18:02:10,485 88183 INFO sama odoo.addons.base.models.ir_attachment: _read_file reading /home/grand-as/.local/share/Odoo/filestore/sama/c2/c21721ec3ec2e8d086eebf804e0ede5f25aa14d7 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
        ~^^^^^
  File "/var/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x701641bef2e0>, 2, '', ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/addons/base/models/ir_attachment.py", line 122, in _file_read
    with open(full_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce nom: '/home/grand-as/.local/share/Odoo/filestore/sama/c2/c21721ec3ec2e8d086eebf804e0ede5f25aa14d7'
2025-08-07 18:02:10,486 88183 INFO sama odoo.addons.base.models.ir_attachment: _read_file reading /home/grand-as/.local/share/Odoo/filestore/sama/c2/c2f49a19f3cf050243e62b22cde5072cca84fcaa 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
        ~^^^^^
  File "/var/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x701641bef2e0>, 2, '', ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/addons/base/models/ir_attachment.py", line 122, in _file_read
    with open(full_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce nom: '/home/grand-as/.local/share/Odoo/filestore/sama/c2/c2f49a19f3cf050243e62b22cde5072cca84fcaa'
2025-08-07 18:02:10,487 88183 INFO sama odoo.addons.base.models.ir_attachment: _read_file reading /home/grand-as/.local/share/Odoo/filestore/sama/d9/d92280f55c4634419639d9ea28f781543c5c8210 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
        ~^^^^^
  File "/var/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x701641bef2e0>, 2, '', ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/addons/base/models/ir_attachment.py", line 122, in _file_read
    with open(full_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce nom: '/home/grand-as/.local/share/Odoo/filestore/sama/d9/d92280f55c4634419639d9ea28f781543c5c8210'
2025-08-07 18:02:10,488 88183 INFO sama odoo.addons.base.models.ir_attachment: _read_file reading /home/grand-as/.local/share/Odoo/filestore/sama/ca/cad9804f210a8c1e26c8ebab07b8056b9d5ec66b 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
        ~^^^^^
  File "/var/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x701641bef2e0>, 2, '', ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/addons/base/models/ir_attachment.py", line 122, in _file_read
    with open(full_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce nom: '/home/grand-as/.local/share/Odoo/filestore/sama/ca/cad9804f210a8c1e26c8ebab07b8056b9d5ec66b'
2025-08-07 18:02:10,489 88183 INFO sama odoo.addons.base.models.ir_attachment: _read_file reading /home/grand-as/.local/share/Odoo/filestore/sama/10/103505c4c49786053392e3df5d2390f31a2fc4a2 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
        ~^^^^^
  File "/var/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x701641bef2e0>, 2, '', ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/addons/base/models/ir_attachment.py", line 122, in _file_read
    with open(full_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce nom: '/home/grand-as/.local/share/Odoo/filestore/sama/10/103505c4c49786053392e3df5d2390f31a2fc4a2'
2025-08-07 18:02:10,491 88183 INFO sama odoo.addons.base.models.ir_attachment: _read_file reading /home/grand-as/.local/share/Odoo/filestore/sama/74/744fc247b813c44f4cf02357706e88b283cb0f97 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
        ~^^^^^
  File "/var/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x701641bef2e0>, 2, '', ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/addons/base/models/ir_attachment.py", line 122, in _file_read
    with open(full_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce nom: '/home/grand-as/.local/share/Odoo/filestore/sama/74/744fc247b813c44f4cf02357706e88b283cb0f97'
2025-08-07 18:02:10,492 88183 INFO sama odoo.addons.base.models.ir_attachment: _read_file reading /home/grand-as/.local/share/Odoo/filestore/sama/3d/3d7a7360fe4a73a90dd3b4ba554a9254ed61e864 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
        ~^^^^^
  File "/var/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x701641bef2e0>, 2, '', ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/addons/base/models/ir_attachment.py", line 122, in _file_read
    with open(full_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce nom: '/home/grand-as/.local/share/Odoo/filestore/sama/3d/3d7a7360fe4a73a90dd3b4ba554a9254ed61e864'
2025-08-07 18:02:10,493 88183 INFO sama odoo.addons.base.models.ir_attachment: _read_file reading /home/grand-as/.local/share/Odoo/filestore/sama/b7/b73a9deb85def8a1a00e4d545c4f79747d78f487 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
        ~^^^^^
  File "/var/odoo/odoo18-venv/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x701641bef2e0>, 2, '', ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/addons/base/models/ir_attachment.py", line 122, in _file_read
    with open(full_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce nom: '/home/grand-as/.local/share/Odoo/filestore/sama/b7/b73a9deb85def8a1a00e4d545c4f79747d78f487'
2025-08-07 18:02:11,163 88183 INFO sama werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:11] "GET /odoo/apps HTTP/1.1" 200 - 96 0.100 0.781
2025-08-07 18:02:13,617 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:02:13,629 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:13] "GET /web/webclient/load_menus/c4aaed515aa9b250f6d3ee386a3317b89e755c60f13f6d0dff13c04f87a8acf5 HTTP/1.1" 500 - 0 0.000 2.119
2025-08-07 18:02:13,625 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:02:13,628 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:02:13,623 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:02:13,633 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:13] "GET /web/webclient/translations/82331042c3a7e910c7ee1cd70c52423d071a9363?lang=en_US HTTP/1.1" 500 - 0 0.000 2.105
2025-08-07 18:02:13,636 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:13] "GET /web/assets/e8e9269/web.assets_web.min.js HTTP/1.1" 500 - 0 0.000 2.205
2025-08-07 18:02:13,638 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:13] "GET /web/assets/5683a52/web.assets_web.min.css HTTP/1.1" 500 - 0 0.000 2.234
2025-08-07 18:02:13,833 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:02:13,836 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:13] "GET /web/assets/a473b93/web.assets_web_print.min.css HTTP/1.1" 500 - 0 0.000 0.132
2025-08-07 18:02:15,036 88183 INFO sama werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:15] "GET /web/manifest.webmanifest HTTP/1.1" 200 - 9 0.008 0.018
2025-08-07 18:02:16,639 88183 INFO sama werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:16] "GET /web/service-worker.js HTTP/1.1" 200 - 1 0.001 0.003
2025-08-07 18:02:18,577 88183 INFO sama werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:18] "GET /odoo/apps HTTP/1.1" 200 - 15 0.011 0.035
2025-08-07 18:02:18,928 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:02:18,930 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:18] "GET /web/assets/5683a52/web.assets_web.min.css HTTP/1.1" 500 - 0 0.000 0.299
2025-08-07 18:02:19,134 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:02:19,135 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:02:19,149 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:19] "GET /web/assets/e8e9269/web.assets_web.min.js HTTP/1.1" 500 - 0 0.000 0.516
2025-08-07 18:02:19,142 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:19] "GET /web/webclient/load_menus/c4aaed515aa9b250f6d3ee386a3317b89e755c60f13f6d0dff13c04f87a8acf5 HTTP/1.1" 500 - 0 0.000 0.438
2025-08-07 18:02:19,211 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:02:19,220 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:19] "GET /web/webclient/translations/82331042c3a7e910c7ee1cd70c52423d071a9363?lang=en_US HTTP/1.1" 500 - 0 0.000 0.470
2025-08-07 18:02:19,259 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:02:19,261 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:19] "GET /web/assets/a473b93/web.assets_web_print.min.css HTTP/1.1" 500 - 0 0.000 0.308
2025-08-07 18:02:20,716 88183 INFO sama werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:20] "GET /web/manifest.webmanifest HTTP/1.1" 200 - 7 0.028 0.029
2025-08-07 18:02:20,825 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:02:20,827 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:02:20] "GET /web/static/img/favicon.ico HTTP/1.1" 500 - 0 0.000 0.145
2025-08-07 18:04:55,384 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:04:55,388 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:04:55] "GET /web/static/src/start.js HTTP/1.1" 500 - 0 0.000 0.112
2025-08-07 18:07:51,992 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Notification: Notify scheduled messages' (8) starting 
2025-08-07 18:07:52,003 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Notification: Notify scheduled messages' (8) done in 0.011s 
2025-08-07 18:07:52,012 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Notification: Notify scheduled messages' (8) processed 0 records, 0 records remaining 
2025-08-07 18:07:52,019 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Notification: Notify scheduled messages' (8) completed 
2025-08-07 18:07:52,038 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Mail: Email Queue Manager' (3) starting 
2025-08-07 18:07:52,064 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Mail: Email Queue Manager' (3) done in 0.026s 
2025-08-07 18:07:52,083 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Mail: Email Queue Manager' (3) processed 0 records, 0 records remaining 
2025-08-07 18:07:52,087 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Mail: Email Queue Manager' (3) completed 
2025-08-07 18:07:52,108 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Partner Autocomplete: Sync with remote DB' (13) starting 
2025-08-07 18:07:52,112 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Partner Autocomplete: Sync with remote DB' (13) done in 0.004s 
2025-08-07 18:07:52,124 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Partner Autocomplete: Sync with remote DB' (13) processed 0 records, 0 records remaining 
2025-08-07 18:07:52,128 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Partner Autocomplete: Sync with remote DB' (13) completed 
2025-08-07 18:08:36,696 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'SMS: SMS Queue Manager' (14) starting 
2025-08-07 18:08:36,702 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'SMS: SMS Queue Manager' (14) done in 0.006s 
2025-08-07 18:08:36,712 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'SMS: SMS Queue Manager' (14) processed 0 records, 0 records remaining 
2025-08-07 18:08:36,718 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'SMS: SMS Queue Manager' (14) completed 
2025-08-07 18:08:36,737 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Snailmail: process letters queue' (15) starting 
2025-08-07 18:08:36,747 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Snailmail: process letters queue' (15) done in 0.010s 
2025-08-07 18:08:36,762 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Snailmail: process letters queue' (15) processed 0 records, 0 records remaining 
2025-08-07 18:08:36,766 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Snailmail: process letters queue' (15) completed 
2025-08-07 18:22:07,269 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Digest Emails' (17) starting 
2025-08-07 18:22:09,083 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Digest Emails' (17) done in 1.814s 
2025-08-07 18:22:09,092 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Digest Emails' (17) processed 0 records, 0 records remaining 
2025-08-07 18:22:09,096 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Digest Emails' (17) completed 
2025-08-07 18:37:25,343 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Event: Mail Scheduler' (18) starting 
2025-08-07 18:37:25,477 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Event: Mail Scheduler' (18) done in 0.134s 
2025-08-07 18:37:25,493 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Event: Mail Scheduler' (18) processed 0 records, 0 records remaining 
2025-08-07 18:37:25,508 88183 INFO sama odoo.addons.base.models.ir_cron: Job 'Event: Mail Scheduler' (18) completed 
2025-08-07 18:46:32,332 88183 INFO sama werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:32] "GET / HTTP/1.1" 200 - 10 0.036 0.142
2025-08-07 18:46:32,700 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:46:32,703 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:32] "GET /web/static/src/libs/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 500 - 0 0.000 0.296
2025-08-07 18:46:32,705 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:46:32,709 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:32] "GET /web/assets/1/595e895/web.assets_frontend.min.css HTTP/1.1" 500 - 0 0.000 0.269
2025-08-07 18:46:32,850 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:46:32,852 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:32] "GET /web/assets/1/0a117f0/web.assets_frontend_minimal.min.js HTTP/1.1" 500 - 0 0.000 0.135
2025-08-07 18:46:33,247 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:46:33,249 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:33] "GET /web/image/website/1/logo/My%20Website?unique=1a52ef8 HTTP/1.1" 500 - 0 0.000 0.446
2025-08-07 18:46:33,251 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:46:33,254 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:33] "GET /web/image/website/1/favicon?unique=1a52ef8 HTTP/1.1" 500 - 0 0.000 0.364
2025-08-07 18:46:33,256 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:46:33,258 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:33] "GET /web/static/img/odoo_logo_tiny.png HTTP/1.1" 500 - 0 0.000 0.451
2025-08-07 18:46:35,933 88183 INFO sama werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:35] "GET / HTTP/1.1" 200 - 10 0.020 0.088
2025-08-07 18:46:36,357 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:46:36,362 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:36] "GET /web/static/src/libs/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 500 - 0 0.000 0.360
2025-08-07 18:46:36,414 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:46:36,429 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:36] "GET /web/assets/1/595e895/web.assets_frontend.min.css HTTP/1.1" 500 - 0 0.000 0.413
2025-08-07 18:46:36,615 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:46:36,617 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:36] "GET /web/assets/1/0a117f0/web.assets_frontend_minimal.min.js HTTP/1.1" 500 - 0 0.000 0.222
2025-08-07 18:46:36,874 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:46:36,893 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:36] "GET /web/static/img/odoo_logo_tiny.png HTTP/1.1" 500 - 0 0.000 0.354
2025-08-07 18:46:36,926 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:46:36,944 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:36] "GET /web/image/website/1/logo/My%20Website?unique=1a52ef8 HTTP/1.1" 500 - 0 0.000 0.408
2025-08-07 18:46:36,997 88183 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 463, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `18.0.x.y` or `18.0.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/odoo/odoo18/odoo/http.py", line 2528, in __call__
    if self.get_static_file(httprequest.path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2427, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
                      ^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/tools/func.py", line 42, in __get__
    value = self.fget(obj)
            ^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/http.py", line 2397, in statics
    manifest = get_manifest(module)
               ^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 363, in get_manifest
    return copy.deepcopy(_get_manifest_cached(module, mod_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 367, in _get_manifest_cached
    return load_manifest(module, mod_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoo18/odoo/modules/module.py", line 346, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module sama_promis: invalid manifest
2025-08-07 18:46:37,000 88183 INFO ? werkzeug: 127.0.0.1 - - [07/Aug/2025 18:46:37] "GET /web/image/website/1/favicon?unique=1a52ef8 HTTP/1.1" 500 - 0 0.000 0.335
